---
version: '3.9'

services:
  db:
    image: postgres:16.9-bookworm
    environment:
      POSTGRES_DB: app
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2-bookworm
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres@db:5432/app
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["/opt/venv/bin/python", "-m", "celery", "-A", "config", "worker", "-l", "info"]
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
